# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ecologial Dynamics & Forecasting
email: forecasting-dynamics-course@weecology.org
description: > # this means to ignore newlines until "baseurl:"
  Morgan Ernest and Ethan White's course on Ecological Dynamics and Forecasting.
  Taught at the University of Florida in Fall 2017.
url: "https://weecology.github.io/forecasting-dynamics-course" # the base hostname & protocol for your site
twitter_username: weecology
github_username:  weecology

# Build settings
markdown: kramdown
